name: backend
services:
  postgres:
    extends:
      file: docker-compose.yaml
      service: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.yaml
      service: redis
    ports:
      - "6379:6379"
  minio:
    extends:
      file: docker-compose.yaml
      service: minio
    ports:
      - "9000:9000"
      - "9001:9001"
#  kafka:
#    extends:
#      file: docker-compose.yaml
#      service: kafka
#    ports:
#      - 9092:9092
#    volumes:
#      - kafka_data:/bitnami
#  pgadmin:
#    extends:
#      file: docker-compose.yaml
#      service: pgadmin
#    ports:
#      - 5050:5050
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgdata:
#  kafka_data:
  minio_data:
#  pgadmin_data: