environment: dev
servers:
  http:
    host: ""
    port: 8080
    timeout: 5s
connections:
  postgres:
    username: user
    password: hard_password1234
    host: postgres
    port: 5432
    dbName: database
    sslEnabled: disable
  redis:
    host: localhost
    port: 6379
  s3:
    endpoint: minio:9000
    accessKey: <your_access_key>
    secretKey: <your_secret_key>
    useSsl: false
  songs:
    host: localhost
    port: 5051
    retries: 5
    timeout: 5s
secrets:
  public: <your_public_key>